---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rockylinux-8
    image: rockylinux/rockylinux:8
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
