---
- name: Create borgbackup timer
  when:
    - install_backup is not defined or install_backup
    - borgmatic_timer is defined and borgmatic_timer == "systemd"
  tags:
    - install_backup
  block:
    - name: Timer Systemd
      ansible.builtin.include_tasks:
        file: noauto_create_timer.yml

- name: Create borgbackup cron
  when:
    - install_backup is not defined or install_backup
    - borgmatic_timer is defined or not borgmatic_timer == "systemd"
  tags:
    - install_backup
  block:
    - name: Install cron backup job
      ansible.builtin.include_tasks:
        file: noauto_create_cronjobs.yml
