---
- name: Install timer to run Borgmatic
  when:
    - borgmatic_timer is defined and borgmatic_timer | length > 0
    - borg_install_method != "docker"
  block:
    - name: Start timer install script
      ansible.builtin.include_tasks:
        file: noauto_create_timer_{{ borgmatic_timer }}.yml
