---
- name: Create borgbackup timer
  when:
    - borgmatic_timer is defined and borgmatic_timer | length > 0
  tags:
    - install_backup
  block:
    - name: Start timer install script
      ansible.builtin.include_tasks:
        file: noauto_create_timer_{{ borgmatic_timer }}.yml
