---
- name: Create borgbackup timer
  when:
    - borgmatic_timer is defined and borgmatic_timer == "systemd"
  tags:
    - install_backup
  block:
    - name: Copy systemd files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        backup: true
        mode: "{{ item.mode }}"
      with_items:
        - { src: "backup.timer.j2", dest: "/usr/lib/systemd/system/backup.timer", mode: "0644" }
        - { src: "backup.service.j2", dest: "/usr/lib/systemd/system/backup.service", mode: "0644" }

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Restart borgmatic services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
        masked: false
        daemon_reload: true
      when: "item in services"
      with_items:
        - backup.service
    
    # bug: Need own section without masked else the timer are skipped
    - name: Restart borgmatic timers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
        daemon_reload: true
      with_items:
        - "backup.timer"
...
