---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: centos:7
  - name: centos-latest
    image: centos:latest
  - name: fedora-latest
    image: fedora:latest
  - name: fedora-31
    image: fedora:31
  - name: debian-oldstable
    image: debian:oldstable
  - name: debian-stable
    image: debian:stable
  - name: ubuntu-bionic
    image: ubuntu:bionic
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  name: ansible
verifier:
  name: ansible
