---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux-latest
    image: archlinux:latest
  - name: almalinux-9
    image: almalinux:9
  # - name: fedora-latest
  #   image: fedora:latest
  - name: debian-bookworm
    image: debian:bookworm
  - name: ubuntu-latest
    image: ubuntu:latest
  # TODO: setup ansible<10 for this
  # - name: rockylinux-8
  #   image: rockylinux/rockylinux:8
  - name: rockylinux-9
    image: rockylinux/rockylinux:9
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
