---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux-latest
    image: archlinux:latest
  - name: almalinux-10
    image: almalinux:10
  - name: debian-trixie
    image: debian:trixie
  - name: ubuntu-resolute
    image: ubuntu:resolute
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
